version: "3.9"

services:
  db:
    container_name: postgres_db
    image: postgres:16.2-alpine3.19
    restart: always
    shm_size: 256mb
    env_file: .env.docker
    command: -p ${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    command: --port ${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env.docker
    networks:
      - backend

  fastapi:
    container_name: fastapi_server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    command: sh -c "PYTHONPATH=$(pwd) python app/main.py"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/code/app
    env_file:
      - .env.docker
    networks:
      - backend
    depends_on:
      - db
      - redis

networks:
  backend:
    driver: bridge
