name: export requirements

on:
  push:
    paths:
      - "pyproject.toml"
      - "poetry.lock"

permissions:
  contents: write

jobs:
  export-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Export requirements.txt
        run: poetry export --without-hashes --format=requirements.txt > requirements.txt

      - name: Commit requirements.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update requirements.txt autocommit. By .github/workflows/export_requirements.yaml"
          file_pattern: "requirements.txt"
