name: post-commit

on:
  push:
    paths:
      - "app/**/*.py"
      - "pyproject.toml"
      - "poetry.lock"

permissions:
  contents: write

jobs:
  post-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Export requirements.txt
        run: poetry export --without-hashes --format=requirements.txt > requirements.txt

      - name: Install Ruff
        run: python -m pip install ruff

      - name: Ruff code check
        run: ruff check app/

      - name: Ruff sorting imports
        run: ruff check app/ --select I --fix

      - name: Ruff code format
        run: ruff format app/

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Post-commit autocommit. By .github/workflows/post-commit.yaml"
          file_pattern: "app/**/*.py"
