USERS_PAGE_LIMIT: int = 10
COMPANIES_PAGE_LIMIT: int = 5
COMPANIES_MEMBERS_PAGE_LIMIT: int = 20
COMPANIES_USERS_REQUEST_PAGE_LIMIT: int = 20

QUIZ_PAGE_LIMIT: int = 5

# redis
USER_QUIZ_ANSWERS_EXPIRE_TIME: int = 60 * 60 * 48
